# application.yml

# Server configurations
server:
  port: 9090

# Database configurations
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AGameDatabase
    username: zavoloka
    password: Z@v010ka
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Logging configurations
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.game: DEBUG

# Custom game-related properties
game:
  title: "My Awesome Game"
  version: "1.0"
  max-players: 100
  initial-coins: 1000
  default-language: en

# Security configurations
security:
  jwt:
    secret-key: your_secret_key
    expiration-time: 86400000 # 24 hours in milliseconds
